name: company_hub
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  _fe_analyzer_shared: ^55.0.0
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.8.0
  flutter_iconly: ^1.0.2
  flutter_native_splash: ^2.2.19
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.5
  form_builder_validators: ^8.3.0
  freezed: ^2.3.2
  get: ^4.6.5
  get_storage: ^2.1.1
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  image_picker: ^0.8.7
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  logger: ^1.2.2
  lottie: ^2.3.2
  modal_bottom_sheet: ^3.0.0-pre
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  pull_to_refresh: ^2.0.0
  retrofit: any
  retrofit_generator: any
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  sizer: ^2.0.15
  table_calendar: ^3.0.8

dev_dependencies:
  build_runner: any
  flutter_gen_runner: null
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/resources/

flutter:
  uses-material-design: true
  assets:
    - lib/resources/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
